export interface IUserDetails {
	full_name: string,
	email: string,
	mobile: string,
	password: string,
	is_verified: boolean,
	gender: string,
	age: number,
	marital_status: string,
	country: string,
	hijab_maintain:any,
	state: string,
	height: number,
	online_status:boolean,
	weight: number,
	body_color: string,
	eye_color: string,
	hair_color: string,
	occupation: string,
	work_place: string,
	monthly_income: string,
	education: string,
	islamic_education: string,
	salah: string,
	sawum: string,
	hajab_maintain: string,
	religious: string,
	fathers_name: string,
	fathers_occupation: string,
	mothers_name: string,
	mothers_occupation: string,
	no_of_brothers: number,
	no_of_sisters: number,
	total_family_member: number,
	financial_condition: string,
	status: string,
	profile_image_url: string,
	device_token: string,
	unseen_message_count: number,
	message_limit: number
}